import React, { Component } from 'react'
import Proxy from "./Proxy"
class App extends Component {
  render() {
    return (
      <div>
        <Proxy/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      </div>
    )
  }
}
export default App
